### ISSUE TITLE
How to access more than 80 entries in 'historyAll'?

### ISSUE THREAD

**Issue by wesleyDM14** [PLCHome/growatt#10]
Hi, 
Your api has helped me a lot, but I've been finding it difficult to access data histories. Is there a way to access the generation data of a specific day and generate with all the daily entries?

**Comment by PLCHome** [comment]
<html>
<body>


historyLastStartDate | new Date() | tomorrow | The start time for retrieving the history.
-- | -- | -- | --
historyLastEndDate | new Date() | yesterday | The end time for retrieving the history.
historyStart | Integer | 0 | The server does not send all data for the time range. With the starting index you get the next rows.


</body>
</html>
Yes, a page can be selected via the "history start" options.
