### ISSUE TITLE
Problems using option "historyLastStartDate" and "historyLastEndDate"

### ISSUE THREAD

**Issue by Nitrouswolf14** [PLCHome/growatt#13]
Hi! I'm developing a dashboard with graphs that show the daily, monthly and annual data of accumulated energy in the inverter.
I have problems getting historical data, using the getAllPlantData function I only get the data for the current day, when trying to use historyLastStartDy historyLastEndDate in options I don't get the data for a whole month.

const startDate = new Date(2023, 5, 09)
const endDate = new Date(2023, 6, 09)
const options = {
                    plantData: true,
                    deviceData: true,
                    deviceTyp: true,
                    weather: false,
                    historyLast:true,
                    historyAll:true,
                    historyLastStartDate: startDate,
                    historyLastEndDate:endDate
            }

Also try using the getHistory function found inside growatt.js, to which I supply the parameters.

const startDate = new Date(2023, 5, 09)
const endDate = new Date(2023, 6, 09)
const getData = await growatt.getHistory('inv', 'XBB9938002', startDate, endDate,0, true);

and the result I get is the error "The server sent an unexpected response, a fatal error has occurred"

**Comment by PLCHome** [comment]
you have set historyAll and HistoryLast this is not possible together because it contradicts itself. historyLast retrieves the last information from historyAll

have you called one of the logins and checked isConnected?

**Comment by Nitrouswolf14** [comment]
sorry for the above error with historyAll and historylast, change options as follows
             const startDate = new Date(2023, 6, 09)
             const endDate = new Date(2023, 5, 09)
                 const options = {
                     plantData: true,
                     deviceData: true,
                     deviceType: true,
                     weather: false,
                     historyLast:false,
                     historyAll:true
                     historyLastStartDate: startDate,
                     historyLastEndDate:endDate
             }
I recover the data with historyAll={}, it does not bring historical data, if I do not provide historyLastStartDate and historyLastEndDate it brings me historyAll with today's data.
Looking at the growatt dashboard I have data for the last days, monthly and for the year 2022.

**Comment by PLCHome** [comment]
startDate must be younger than endDate

<img width="896" alt="image" src="https://github.com/PLCHome/growatt/assets/29116097/f88a8a08-8f86-47cc-b368-2541fd25e2c7">

I think the documentation is wrong
