### ISSUE TITLE
setInverterSetting method not working

### ISSUE THREAD

**Issue by bletru** [PLCHome/growatt#14]
**Describe your inverter**

Growatt 5000-tl3 xh
Shine-X
**Describe the bug**  
Cannot write setting to the inverter.
Method "setInverterSetting" gives an error even for the example given in the README.
Login object is done and plant list is reading correctly as well as the method
"getInverterSetting" works correctly.

**To Reproduce**  
Try to set time of your inverter with example in README.

And if you try to set "pvActivePRate" there is even more error text:
"Error: The value Store is missing for send function pvActivePRate on invertertype tlx
    at D:\Users\Christoph\growatt\node_modules\growatt\lib\growatt.js:645:25
    at Array.forEach (<anonymous>)
    at D:\Users\Christoph\growatt\node_modules\growatt\lib\growatt.js:635:30
    at new Promise (<anonymous>)
    at growatt.comInverter (D:\Users\Christoph\growatt\node_modules\growatt\lib\growatt.js:611:12)
    at growatt.setInverterSetting (D:\Users\Christoph\growatt\node_modules\growatt\lib\growatt.js:606:17)
    at test (D:\Users\Christoph\growatt\test.txt:66:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
"

Should be there a value "Store" defined in the object and what value should it take?

**Expected behavior**  
Response code should be "Success: true" but delivers {msg: 'inv_set_time_format', success: false}

**Screenshots & Logfiles**  
![image](https://github.com/PLCHome/growatt/assets/13706407/57966e8b-de1c-4c51-9987-f4b0feab5a4d)
**Versions:**

- Adapter version: latest
- JS-Controller version: ??? (is iobroker needed?)
- Node version: v18.16.1
- Operating system: Windows 10

**Additional context**

**Comment by PLCHome** [comment]
please change DATETIME in lib/parsein.js for a test:

```
static DATETIME(val) {
    debugApi('DATETIME:', val);
    try {
      const d = new Date(val);
      const year = `000${d.getFullYear()}`.slice(-4);
      const month = `0${d.getMonth() + 1}`.slice(-2);
      const day = `0${d.getDate()}`.slice(-2);
      const hour = `0${d.getHours()}`.slice(-2);
      const minute = `0${d.getMinutes()}`.slice(-2);
      const second = `0${d.getSeconds()}`.slice(-2);
      const res = `${year}-${month}-${day} ${hour}:${minute}:${seconds}`;
      return [res, /^[0-9][0-9][0-9][0-9]-(1[0-2]|0[1-9])-(3[0-1]|[0-2][0-9]) (2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])$/.test(res)];
    } catch (Error) {
      return [0, false];
    }
  }
```

**Comment by bletru** [comment]
Thanks for your response, but I found the bug myself:

In the parameter object "v" you have always to specify "param2: true" in addition to "param1: xxxx" otherwise the object is not complete and API is complaining.

Thus for time setting:

let v = { param1: 1687600871000, param2: true };

works. And for the "pvActivePRate" the argument object should be:

let v1 = { param1: 30, param2: true };

e.g. here the full code to set Active Power Rate:

  let v1 = {param1: 30, param2: true};
  let type1 = "tlx";
  let name1 = "pvActivePRate";
  let sn1 = "<your inverter sn>";
  let result1 = await growatt.setInverterSetting (type1, name1, sn1, v1).catch(e => {console.log(e)});
  console.log (result1);

I let you test and correct the example code.

**Comment by PLCHome** [comment]
ist the SPH5000-tl3 xh really an tlx?
the SPH5000 is an mix

**Comment by PLCHome** [comment]
I just looked at the recordings in the forum and the seconds are being sent there. However, they are missing when querying. Hence the error. not that the byte was simply missing and he gets the seconds on Param2.

**Comment by bletru** [comment]
Oh sorry, my inverter is a MOD5000 not SPF ...

**Comment by PLCHome** [comment]
![image](https://github.com/PLCHome/growatt/assets/29116097/b351de8d-f511-4b98-b6bb-4b7dc20814a8)

For the time he probably needs seconds, no second parameter.

Setting Active Power Rate requires 2 parameters the percentage and whether the value should be saved. This is also the answer when you query the parameters.

`<inst>getInverterCommunication('tlx')`

**Comment by PLCHome** [comment]
I can't test anything here because I don't own the inverter type. I'll add the seconds to time.

**Comment by PLCHome** [comment]
> Thanks for your response, but I found the bug myself:
> 
> In the parameter object "v" you have always to specify "param2: true" in addition to "param1: xxxx" otherwise the object is not complete and API is complaining.
> 
> Thus for time setting:
> 
> let v = { param1: 1687600871000, param2: true };
> 
> works. And for the "pvActivePRate" the argument object should be:
> 

That's wrong

```
let v = { param1: 1687600871000 };

let type1 = "tlx";
let name1 = "pvActivePRate";
let sn1 = "";
let result1 = await growatt.setInverterSetting (type1, name1, sn1, v).catch(e => {console.log(e)});
console.log (result1);

```
must Work.

Check out
```
let type1 = "tlx";
let result1 = await growatt.getInverterCommunication(type1).catch(e => {console.log(e)});
console.log (JSON.stringify(result1));

```
