### ISSUE TITLE
server.growatt.com no login possible since tens of hours ...

### ISSUE THREAD

**Issue by bletru** [PLCHome/growatt#15]
**Describe your inverter**

Growatt MOD5000-tl3 xh
Shine-X

**Describe the bug**  
The server 

https://server.growatt.com

does not work for more than 12 hours.
I am able to connect through the ShineWifi application but there is no
API for this way. Is there any way to bypass server.growatt.com login in order
to access the inverter?

**To Reproduce**  
Try to login at

https://server.growatt.com

**Screenshots & Logfiles**  
![Capture d’écran 2023-06-26 110926](https://github.com/PLCHome/growatt/assets/13706407/96a29477-fa25-4d5d-a54a-d109787e0939)

Log of API:

Error: {"result":-5,"msg":"temporarily unavailable"}
    at /var/www/html/nodejs/node_modules/growatt/lib/growatt.js:142:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by PLCHome** [comment]
Please contact Growatt. If you can't log in there, of course, this adapter doesn't work.

**Comment by PLCHome** [comment]
The login should not occur with every query. The values ​​should not be queried too often, maximum one minute. Eventually the server will shut down for you.

**Comment by bletru** [comment]
"The login should not occur with every query"

Yes and no. My initial approach was to launch a script through "cron" and thus there is a login on each launch.
I suppose to make a version where the credential token is saved for future usage in order to not login each time.
If Growatt API would provide all these informations and allow settings through API, there would be no need for so complicated circumventions, but what to do for make Growatt moving?

**Comment by PLCHome** [comment]
My tip: use a ready-made product like Node red or ioBroker. You don't have to tinker and knit.
