### ISSUE TITLE
TLXH Type Module Data no Returned

### ISSUE THREAD

**Issue by mumblebaj** [PLCHome/growatt#17]
**Describe your inverter**

Typ, modell, ...
tlx, MIN 3600TL-XH
The enviroment (panels, accu etc.)

The modell of the logger
ShineWiFi-X

**Describe the bug**  
A user of one of my modules have two Growatt inverters, Growatt 3600MTL-S and MIN 3600TL-XH. The type of the MTL-S is inv and TL-XH is tlx. Neither of the two is returning statusData. When browsing the module code the inv does not seem to implement a method to get statusData but the tlx does. For some reason it does not seem to be getting the information for the tlx. When manually running the call that the tlx model should be calling it does return data.  See below.

```
{
    "result": 1,
    "obj": {
        "ptoStatus": "592",
        "pdisCharge1": "0",
        "pactouser": "0",
        "vBat": "209.7",
        "SOC1": "0",
        "SOC2": "0",
        "chargePower1": "0",
        "vAc1": "240.8",
        "chargePower2": "0",
        "bdcStatus": "1",
        "pdisCharge": "50",
        "lost": "tlx.status.checking",
        "pactogrid": "53.8",
        "pLocalLoad": "538.3",
        "vPv2": "153.5",
        "vPv3": "0",
        "vPv1": "153.3",
        "chargePower": "0",
        "operatingMode": "0",
        "upsVac1": "0",
        "SOC": "15",
        "pPv2": "267.8",
        "pPv3": "0",
        "fAc": "50",
        "pPv4": "0",
        "vac1": "240.8",
        "vPv4": "0",
        "pPv1": "274.3",
        "upsFac": "0",
        "ppv": "542.1",
        "pdisCharge2": "0",
        "status": "1"
    }
}
```

**To Reproduce**  

2. Click on '...'

**Expected behavior**  
Expecting statusData returned for the tlx device type. But getting the following returned instead. 

```
  devices: {
    _INV-TYPE_: {
      totalData: [Object],
      historyLast: [Object],
      deviceData: [Object]
    },
    _TLX-TYPE_: { deviceData: [Object] }
  }
```
Options selected:

```
const options = {
  plantData: true, weather: false, totalData: true, **statusData: true**, deviceData: true,
  deviceType: false, historyLast: true, historyAll: false
}
```

**Comment by PLCHome** [comment]
Which version are you using, is it the current one?

I thought it was fixed

https://github.com/mumblebaj/MMM-Growatt/blob/cc489d1d2076ce1a19107b17925eb9ee128bebb3/package.json#L13

0.4.0: Maintenance Release
Enhancements

Status data now also from TLX/TLXH

**Comment by PLCHome** [comment]
I also recommend evaluating last history. It contains all data that came last from the logger. Especially for inv

**Comment by mumblebaj** [comment]
Hi. I am using "growatt": "^0.5.6" in my latest module [MMM-Growatt-Stats](https://github.com/mumblebaj/MMM-Growatt-Stats.git). historyLast does not carry all the data to build the views. I think the issue comes in if there are multiple  devices connected to the system. I am getting the data returned for the first device in the list but not for the second device which is the TLX one.

I.e. it makes the available call for the first device but not the second. The second device is the TLX which should return statusData from `panel/tlx/getTLXStatusData_bdc` but it does not seem to get called.

```
  devices: {
    CXXXXXX02X: {
      totalData: [Object],
      historyLast: [Object],
      deviceData: [Object]
    },
    RXXXXXX01X: { deviceData: [Object] }
  }
```

**Comment by mumblebaj** [comment]
My apologies, I have updated to the latest version and I am now getting the required data.  Thank you for the assistance.

**Comment by mumblebaj** [comment]
Hi. Just one more thing I have picked up,  the call returns the required data now but it seems to double up on the results. 

I am seeing 2 sets of devicesData whereas I would expect only one set.

![image](https://github.com/PLCHome/growatt/assets/39963138/17e63d77-24f7-4823-92bc-45c255c9c4e6)


![image](https://github.com/PLCHome/growatt/assets/39963138/d8fb3b93-549b-4a54-97c7-6973a3272306)

If you could possibly have a look at this and advise?
