### ISSUE TITLE
Only one historyLast per plant

### ISSUE THREAD

**Issue by maufc** [PLCHome/growatt#2]
Hello.
We have several plants (4) each with 2-3 inverters.
When I run growatt.js, I get almost full information: plants information, including the devices (inverters) of each plant. I can get the totalData, historyLast and deviceData properties for the first device listed of each plant BUT only deviceData for the second and the third.
I am pretty sure that it is a 'for' problem in some functions on /lib/growatt.js where the only index called is [0] but I can't solve it.
I tried to call the function directly to discard API problem but I couldn't neither.
I will appreciate if you can take a look.
Thanks!

**Comment by PLCHome** [comment]
Please send me an Key for a Week or a Month then i can look what i can do for you.
You can log into the forum over Github and send me the key via PM: [ioBroker Forum](https://forum.iobroker.net/user/plchome-0)

**Comment by maufc** [comment]
Hi. Sorry for take that much time to answer. I can't generate a key. The option doesn't appear in my account.
For more information, my devices are all MAX devices (big ones about 50KW). I can use the individual function without problems but the complete main function gives incomplete data as post before.
Thanks!
