### ISSUE TITLE
Unhandled Rejection (TypeError): Axios.create is not a function

### ISSUE THREAD

**Issue by szopenkrk** [PLCHome/growatt#20]
**Describe your inverter**

Typ, modell, ...
The enviroment (panels, accu etc.)
The modell of the logger

**Describe the bug**  

**To Reproduce**  

2. Click on '...'

**Expected behavior**  
After add growat package to react js I get that error 

**Screenshots & Logfiles**  
![Zrzut ekranu 2023-09-19 o 18 32 53](https://github.com/PLCHome/growatt/assets/4053844/8cdbfac4-91f6-4b0a-9ddf-8da4f9bcfa10)

**Versions:**

- Adapter version: <adapter-version>
- JS-Controller version: <js-controller-version> 
- Node version: <node-version> 
- Operating system: <os-name>

**Additional context**

**Comment by PLCHome** [comment]
Node version missing
Make a project
Please use NPM to install

tested on dev System Node 20.7.0: ok

**Comment by szopenkrk** [comment]
@PLCHome Hi I have another case where I get the error login reject: {result: -2, msg: 'Błąd hasła'} -2 password is the same on the platform https://oss.growatt.com/ and in the code any ideas?

**Comment by szopenkrk** [comment]
From postman i have the same maybe You had that kind of issue when You have installer account

**Comment by PLCHome** [comment]
It is not for oss.growatt.de the note its only for server.growatt.com and server-us.growatt.com. There is a NOTE that has implemented this API. You can try indexCandI. But this shouldn't make any difference since the registration is the same.
