### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Sweenylein** [PLCHome/growatt#21]
Hi,

Not long ago it worked without any problems, but now it doesn't?

See error message:

login: undefined
Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
    at xxxx\growatt\lib\growatt.js:302:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
getAllPlatData: undefined
logout: { result: 1, msg: 'OK' }

I used version 0.7.1

Has anything changed on the Growatt server? There is also a discussion here: https://github.com/home-assistant/core/issues/100874

Kind regards
Alex

**Comment by PLCHome** [comment]
![image](https://github.com/PLCHome/ioBroker.growatt/assets/29116097/59ad1601-7170-47fd-86ac-0beb79f7e7f7)
![image](https://github.com/PLCHome/ioBroker.growatt/assets/29116097/8160eddf-6df1-400c-a5fe-5b5c6869d4e3)

There are probably cloud problems at the moment. The app doesn't work properly either. Unfortunately I have no influence on the website. Please contact Growatt


This node requires a working website. The website is currently sporadically not providing any data, the node cannot obtain any data.
Either the login is rejected with result -1 or the response is 500, which indicates a server error.

**Comment by Sweenylein** [comment]
Hi @PLCHome,

thanks for your answer.

Your script is still not working for me, but the website and the app are working again. I have the feeling that the API endpoints have been changed by Growatt or the login process?

**Comment by PLCHome** [comment]
I don't know your implementation nor do I know whether you use C and I. There is a reference implementation for the ioBroker, 1500 installations currently use the API. I didn't hear the problem. Generate a KEY if it is really the login issue.
