### ISSUE TITLE
New Login 

### ISSUE THREAD

**Issue by maufc** [PLCHome/growatt#22]
Is the login working with this new validation process?
Cheers, 
![Captura desde 2023-10-04 09-23-17](https://github.com/PLCHome/growatt/assets/47666962/ef72e77d-dc72-4f47-be87-5e450ec0feda)

**Comment by PLCHome** [comment]
I haven't heard that it doesn't work. I have no idea when this input will come. The last time I saw this it was just checked from the website. The login was not informed of this input. Just like the password to change the parameterization. This is checked in the browser's Java code.

If that doesn't work, there is the option to generate a key. If you use the key with the associated login it should work.
