### ISSUE TITLE
Growatt API fails

### ISSUE THREAD

**Issue by tulamidan** [PLCHome/growatt#23]
Recently there were reports from a lot of python based projects that the Growatt API does not allow them in anymore. Today this also started for me using your node approach.
Maybe this is temporary - but maybe the code needs adjustments...

**Comment by PLCHome** [comment]
Please send concrete error messages from the API or recordings of communication between the website and the server, not colorful images of the interface. The API doesn't serve the remote page, it goes directly to the calls. If there are problems logging in, the API offers the option of logging in with a key. I haven't seen that yet. Thanks.

There is a template for a reason. I will close the error message directly if it does not contain any specific error messages or debug output.

Please don't waste my time.

**Comment by PLCHome** [comment]
set DEBUG=growatt:api

**Comment by PLCHome** [comment]
Oh, by the way, the Growatt servers don't like it when you log in there too often and starting a program every 30 seconds doesn't work.

If the program wants to start again and again, the cycle should be more then 5 minutes.

It is best to keep the connection open and reconnect if the API reports an error. The method connected() is also offered.

That could be the problem.

**Comment by tulamidan** [comment]
This might very much be the case - in my implementation I logged out on each query - is it known how long it takes to unblock a user again?
Sorry to bother you -I guess this can be closed.

The error btw.
  growatt:api constructor in config: {} +0ms
  growatt:api constructor config: {
  timeout: 50000,
  headers: {},
  server: 'https://server.growatt.com',
  indexCandI: false
} +2ms
  growatt:api login: user: user password: *no* +1ms
mqtt connected
  growatt:api login reject: { result: -5, msg: 'temporarily unavailable' } +259ms
Error: {"result":-5,"msg":"temporarily unavailable"}
    at C:\Users\user\node_modules\growatt\lib\growatt.js:149:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
login: undefined
  growatt:api getAllPlantData options: {} +6ms
  growatt:api getAllPlantData options: { plantData: true, deviceData: true, weather: true } +1ms
  growatt:api getPlatList: +1ms
  growatt:api getPlatList reject +508ms
  growatt:api getAllPlantData getPlatList err: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
    at C:\Users\user\node_modules\growatt\lib\growatt.js:268:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) +0ms
Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
    at C:\Users\user\node_modules\growatt\lib\growatt.js:268:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:

**Comment by PLCHome** [comment]
> `result: -5, msg: 'temporarily unavailable`

The server blocked you because it connected too frequently (-5).
Do not connect to the user for 24h to 48h then connect for a maximum 15 minutes.
I suspect that's why you get the chepta.

Something is wrong with your code, the login reports an error and you request your data.
> `error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin`

Querying data without login requests can also lead to a blocking.
