### ISSUE TITLE
setting the "EMS Discharging Power Rate" on a EU MIN 2500TL-X

### ISSUE THREAD

**Issue by staabm** [PLCHome/growatt#26]
**Describe your inverter**

Inverter: EU MIN 2500TL-X with a battery
Collector: ShineWiFi-X

**Describe the bug**  
I want to set the "EMS Discharging Power Rate" value.
I think I already found the correct `sn` and `growattType=tlxh` within `getAllPlantData`.

I wonder so which value I need to pass for `name` into `growatt.getInverterSetting(type, name, sn)` to read out the current "EMS Discharging Power Rate" value...?

after I am able to read the value, I want to try writing this value via `growatt.setInverterSetting(typ, name sn, v);` - not sure how yet..

so my question is more about: how to find out what all these magic keys mean which are returned by the api?

**Versions:**

- Adapter version: <adapter-version>
- JS-Controller version: <js-controller-version> 
- Node version: v21.6.2
- Operating system: macos sonoma

**Additional context**

**Comment by PLCHome** [comment]
```
    let com = growatt.getInverterCommunication ('tlxh');
    console.log(JSON.stringify(com, null, '  '));
```

name should be: 'pvActivePRate'
the other option is 'time'

**Comment by staabm** [comment]
Thank you. How do you know this keys. Is there documentation somewhere?

**Comment by PLCHome** [comment]
getInverterCommunication  returns the possible settings and describes the values
