### ISSUE TITLE
It has been working for several month, until now

### ISSUE THREAD

**Issue by yrjc** [PLCHome/growatt#30]
If I wait long enough, it will probably start working again. It has done this several times over the years.
But it is quite annoying having to use mobile app or browser login to get my data (the Growatt data is integrated into my power monitoring system).
I am only using user/password options of this API. Now I keep getting 'temporarily unavailable' and 
Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
There is nothing wrong with my login details. 

I wonder if the 'key' option is a more stabile choice ?

**Comment by PLCHome** [comment]
You can't log in too often. The best thing is to establish the connection once and then start a query every few minutes. If the connection breaks down. So after 12 hours it has to be rebuilt.
