### ISSUE TITLE
node-red-contrib-growatt

### ISSUE THREAD

**Issue by Looking4Cache** [PLCHome/growatt#7]
Hi,

thanks for this nice repro. I used it some days ago to access my new inverter through Node-RED. As doing this, I created a small Node that wraps around your library. See here: https://flows.nodered.org/node/node-red-contrib-growatt

It's very simple at the momentan and has some missing stuff (like login with key, caching the login, history time ranges).

Greetings,
Thorsten

**Comment by PLCHome** [comment]
historyLastStartDate, historyLastEndDate and historyStart  you don't need for normal on time operration, the node whill fill this as well automaticlie for historyLast.
It is only required to request for historyAll. But I would install a new node that picks up the history on request.


I don't do anything for node red anymore. I was bombarded with tickets in the Beckhoff Contrib with errors when deploying. After a few Nodred updates the errors were gone and so was I. I no longer program around a buggy system.
