### ISSUE TITLE
Error due to requesting multiple time the growatt server

### ISSUE THREAD

**Issue by BMOussama** [PLCHome/growatt#8]
Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
    at ~./Desktop/monotoring/node_modules/growatt/lib/growatt.js:337:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
undefined

*************************************************

i got this error after requesting multiple time growatt server.
I used only your example code for that.
![error](https://user-images.githubusercontent.com/38170769/173625535-c1b132a2-82de-4c83-9204-8401ebd0b1e4.png)

**Comment by PLCHome** [comment]
The problem is in the error message, the login is rejected by the Growatt server.

Two possibilities:
- The key/password has expired.
- The server is overloaded, then the error occurs in the last few days -> solution: complain to Growatt.
